// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SecuritiesDAL.Models;
using System;

namespace SecuritiesDAL.Migrations
{
    [DbContext(typeof(ExchangeContext))]
    partial class ExchangeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SecuritiesCommon.Exchanges.Exchange", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Close");

                    b.Property<string>("Description");

                    b.Property<string>("Economy");

                    b.Property<int>("ExchangeID");

                    b.Property<string>("Location");

                    b.Property<double>("MarketCap");

                    b.Property<string>("Name");

                    b.Property<DateTime>("Open");

                    b.HasKey("Id");

                    b.ToTable("Exchange");
                });
#pragma warning restore 612, 618
        }
    }
}
